
swagger:
  enable: true
spring:
  datasource:
    url: jdbc:mysql://commondb.cluster-cafvfjfvjsow.eu-west-1.rds.amazonaws.com/push_register
    username: push_register
    password: 'push_register01@#0LZ'
  jpa:
    generate-ddl: false
